-- 创建最终的、经过完整特征工程的事件时间线视图 (版本 5)
CREATE VIEW timeline_engineered_v4 AS

-- 1. 初始诊断 (from timeline_diagnosis) - 已拆分
-- 1a. AJCC分期
SELECT PATIENT_ID, START_DATE, 0 AS EVENT_DURATION, EVENT_TYPE AS EVENT_TYPE, 'AJCC_STAGE' AS EVENT_SUBTYPE, CAST(NULL AS REAL) AS VALUE_NUMERIC, AJCC AS VALUE_CATEGORICAL FROM timeline_diagnosis WHERE AJCC IS NOT NULL AND AJCC != ''
UNION ALL
-- 1b. 临床分组
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, 'CLINICAL_GROUP', CAST(NULL AS REAL), CLINICAL_GROUP FROM timeline_diagnosis WHERE CLINICAL_GROUP IS NOT NULL AND CLINICAL_GROUP != ''
UNION ALL
-- 1c. 病理分组
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, 'PATH_GROUP', CAST(NULL AS REAL), PATH_GROUP FROM timeline_diagnosis WHERE PATH_GROUP IS NOT NULL AND PATH_GROUP != ''
UNION ALL
-- 1d. CDM推导分期
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, 'STAGE_CDM_DERIVED', CAST(NULL AS REAL), STAGE_CDM_DERIVED FROM timeline_diagnosis WHERE STAGE_CDM_DERIVED IS NOT NULL AND STAGE_CDM_DERIVED != ''
UNION ALL

-- 2. 影像学检查程序 (from timeline_cancer_presence) - 已拆分
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, 'IMAGING_CHEST', CAST(NULL AS REAL), PROCEDURE_TYPE FROM timeline_cancer_presence WHERE CHEST = 1
UNION ALL
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, 'IMAGING_ABDOMEN', CAST(NULL AS REAL), PROCEDURE_TYPE FROM timeline_cancer_presence WHERE ABDOMEN = 1
UNION ALL
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, 'IMAGING_PELVIS', CAST(NULL AS REAL), PROCEDURE_TYPE FROM timeline_cancer_presence WHERE PELVIS = 1
UNION ALL
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, 'IMAGING_HEAD', CAST(NULL AS REAL), PROCEDURE_TYPE FROM timeline_cancer_presence WHERE HEAD = 1
UNION ALL
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, 'IMAGING_OTHER', CAST(NULL AS REAL), PROCEDURE_TYPE FROM timeline_cancer_presence WHERE OTHER = 1
UNION ALL

-- 3. 影像学肿瘤位置发现 (from timeline_tumor_sites)
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, 'TUMOR_SITE_' || TUMOR_SITE, CAST(NULL AS REAL), SOURCE_SPECIFIC FROM timeline_tumor_sites WHERE TUMOR_SITE IS NOT NULL AND TUMOR_SITE != ''
UNION ALL

-- 4. 影像学进展 (from timeline_progression)
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, 'IMAGING_PROGRESSION', CAST(NULL AS REAL), PROGRESSION FROM timeline_progression WHERE PROGRESSION IS NOT NULL
UNION ALL

-- 5. 实验室检查 (Unifying all _labs tables)
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, TEST, RESULT, LR_UNIT_MEASURE FROM timeline_cea_labs
UNION ALL
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, TEST, RESULT, LR_UNIT_MEASURE FROM timeline_psa_labs
UNION ALL
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, TEST, CAST(RESULT AS REAL), LR_UNIT_MEASURE FROM "timeline_ca_15-3_labs"
UNION ALL
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, TEST, CAST(RESULT AS REAL), LR_UNIT_MEASURE FROM "timeline_ca_19-9_labs"
UNION ALL

-- 6. 治疗 (from timeline_treatment) - 已拆分
-- 6a. 治疗药物事件
SELECT PATIENT_ID, START_DATE, COALESCE(STOP_DATE - START_DATE, 0) AS EVENT_DURATION, EVENT_TYPE AS EVENT_TYPE, SUBTYPE AS EVENT_SUBTYPE, CAST(NULL AS REAL) AS VALUE_NUMERIC, AGENT AS VALUE_CATEGORICAL FROM timeline_treatment
UNION ALL
-- 6b. 治疗是否为研究性药物事件
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, 'IS_INVESTIGATIVE', CASE WHEN RX_INVESTIGATIVE = 'Y' THEN 1.0 ELSE 0.0 END, CAST(NULL AS TEXT) FROM timeline_treatment
UNION ALL
-- 6c. 治疗是否为局部用药事件
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, 'IS_OROTOPICAL', CAST(FLAG_OROTOPICAL AS REAL), CAST(NULL AS TEXT) FROM timeline_treatment
UNION ALL

-- 7. 放射治疗 (from timeline_radiation)
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, SUBTYPE, CAST(NULL AS REAL), CAST(NULL AS TEXT) FROM timeline_radiation
UNION ALL

-- 8. 先前用药 (from timeline_prior_meds) - 已拆分
-- 8a. 状态：是否有过院外用药
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, 'PRIOR_MEDS_STATUS', CASE WHEN PRIOR_MED_TO_MSK = 'Prior medications to MSK' THEN 1.0 ELSE 0.0 END, CAST(NULL AS TEXT) FROM timeline_prior_meds
UNION ALL
-- 8b. 概率：推断的治疗概率
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, 'PRIOR_MEDS_PROB', INFERRED_TX_PROB, CAST(NULL AS TEXT) FROM timeline_prior_meds
UNION ALL

-- 9. 手术/流程 (from timeline_surgery)
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, 'SURGERY_' || SUBTYPE, CAST(NULL AS REAL), CAST(NULL AS TEXT) FROM timeline_surgery
UNION ALL

-- 10. 病理学检查 (Pathology)
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, SUBTYPE, CAST(GLEASON_SCORE AS REAL), CAST(NULL AS TEXT) FROM timeline_gleason
UNION ALL
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, SUBTYPE, CAST(MMR_ABSENT AS REAL), CAST(NULL AS TEXT) FROM timeline_mmr
UNION ALL
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, SUBTYPE, CASE WHEN PDL1_POSITIVE = 'Yes' THEN 1.0 ELSE 0.0 END, CAST(NULL AS TEXT) FROM timeline_pdl1
UNION ALL

-- 11. 样本事件 (Sample Events)
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, CAST(NULL AS TEXT) AS EVENT_SUBTYPE, CAST(SEQ_DATE AS REAL), CAST(NULL AS TEXT) FROM timeline_specimen_surgery
UNION ALL
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, CAST(NULL AS TEXT) AS EVENT_SUBTYPE, CAST(NULL AS REAL), CAST(NULL AS TEXT) FROM timeline_specimen
UNION ALL

-- 12. 体能状态评估 (from timeline_performance_status)
SELECT PATIENT_ID, START_DATE, 0, EVENT_TYPE, SUBTYPE, CAST(NULL AS REAL), CAST(NULL AS TEXT) FROM timeline_performance_status;

-- 简洁版查询，选择所有列并创建视图
CREATE VIEW prostate_survival_lstm_dataset AS -- brca, crc, nsclc, panc, prostate
SELECT
    t.*, -- 选择 timeline 表的所有列
    b.*  -- 选择 brca 表的所有列
FROM
    timeline_engineered_v4 AS t
INNER JOIN
    source_prostate_dx_1st_seq_OS AS b ON t.PATIENT_ID = b.PATIENT_ID
ORDER BY
    t.PATIENT_ID, t.START_DATE;